### ISSUE TITLE
gpi error about PyQt5

### ISSUE THREAD

**Issue by sunpengmri** [gpilab/framework#69]
Hi
I have installed the newest gpilab in a ubuntu 20.04 system following the instructions https://gpilab.com/downloads/, but failed to start. Here is the error message, any help would be appreciated.

Traceback (most recent call last):
  File "/home/peng/opt/gpi/framework/./bin/gpi", line 38, in <module>
    from gpi import launch
  File "/home/peng/opt/anaconda3/envs/gpi_env/lib/python3.9/site-packages/gpilab-1.4.8-py3.9.egg/gpi/__init__.py", line 68, in <module>
    from . import qtapi
  File "/home/peng/opt/anaconda3/envs/gpi_env/lib/python3.9/site-packages/gpilab-1.4.8-py3.9.egg/gpi/qtapi.py", line 30, in <module>
    import qtpy.QtCore as _QtCore
  File "/home/peng/opt/anaconda3/envs/gpi_env/lib/python3.9/site-packages/qtpy/QtCore.py", line 42, in <module>
    from PyQt5.QtCore import *
ImportError: /home/peng/opt/anaconda3/envs/gpi_env/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

**Comment by joeyplum** [comment]
Hi @sunpengmri,

Were you ever able to fix this issue? I am returning a similar message on my Ubuntu 20.04 system when trying to run gpi after installing.

$ joeyplum@EW23-02019:~/gpi$ ./bin/gpi

...returns...


GPI 1.4.8 (2022-04-08)
This program comes with ABSOLUTELY NO WARRANTY; see the LICENSE for details.

    NO CLINICAL USE.  THE SOFTWARE IS NOT INTENDED FOR COMMERCIAL PURPOSES
AND SHOULD BE USED ONLY FOR NON-COMMERCIAL RESEARCH PURPOSES.  THE SOFTWARE
MAY NOT IN ANY EVENT BE USED FOR ANY CLINICAL OR DIAGNOSTIC PURPOSES.  YOU
ACKNOWLEDGE AND AGREE THAT THE SOFTWARE IS NOT INTENDED FOR USE IN ANY HIGH
RISK OR STRICT LIABILITY ACTIVITY, INCLUDING BUT NOT LIMITED TO LIFE SUPPORT
OR EMERGENCY MEDICAL OPERATIONS OR USES.  LICENSOR MAKES NO WARRANTY AND HAS
NO LIABILITY ARISING FROM ANY USE OF THE SOFTWARE IN ANY HIGH RISK OR STRICT
LIABILITY ACTIVITIES.

Traceback (most recent call last):
  File "/home/joeyplum/gpi/./bin/gpi", line 38, in <module>
    from gpi import launch
  File "/home/joeyplum/anaconda3/envs/gpu_env/lib/python3.9/site-packages/gpi/__init__.py", line 72, in <module>
    QtMultimedia = qtapi.import_module("QtMultimedia")
  File "/home/joeyplum/anaconda3/envs/gpu_env/lib/python3.9/site-packages/gpi/qtapi.py", line 37, in import_module
    p = __import__('qtpy', globals(), locals(), [moduleName], 0)
  File "/home/joeyplum/anaconda3/envs/gpu_env/lib/python3.9/site-packages/qtpy/QtMultimedia.py", line 8, in <module>
    from PyQt5.QtMultimedia import *
ImportError: libpulse-mainloop-glib.so.0: cannot open shared object file: No such file or directory
